---
language: python
sudo: false
python:
  - 2.7
  - 3.5
install: pip install -r requirements.txt
script:
  - yamllint -s $(git ls-files | grep -E '*.ya?ml$')
  - ansible-lint playbook.yml
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook -i ci_hosts playbook.yml --syntax-check
  - ansible-playbook -i ci_hosts playbook.yml --connection=local --sudo
