---
language: python
sudo: false
python:
  - 2.7
  - 3.5
matrix:
  include:
    - install: pip install -r requirements.txt
      script:
        - yamllint -s $(git ls-files | grep -E '*.ya?ml$')
        - ansible-lint playbook.yml
